# Generated by Django 4.1.5 on 2023-01-31 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_documents_post_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='name',
        ),
    ]
