# Generated by Django 4.1.5 on 2023-01-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_documents_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Text'),
        ),
    ]
