# Generated by Django 4.1.5 on 2023-02-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='post_id',
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('img', 'img'), ('video', 'video'), ('iframe', 'iframe')], default='iframe', max_length=6),
        ),
    ]
