# Generated by Django 4.1.5 on 2023-01-23 06:24

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_delete_department_remove_user_is_candidate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(
                default="IQ", max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Job title"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=60, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="firstname",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="lastname",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Last name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                default="photos/default.jpg", upload_to="avatars", verbose_name="Avatar"
            ),
        ),
    ]
