# Generated by Django 4.1.5 on 2023-01-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_country_user_job_title_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="firstname",
            field=models.CharField(
                default="", max_length=30, verbose_name="First name"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="job_title",
            field=models.CharField(default="", max_length=30, verbose_name="Job title"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="lastname",
            field=models.CharField(default="", max_length=30, verbose_name="Last name"),
            preserve_default=False,
        ),
    ]
